### PR TITLE
/ssb doesnt exist. Commenting out message in Essb.

### PR DESCRIPTION
**Pull request by Stellation**
Also added my quotes

### CODE REVIEW

**Comment by Stellation** [comment]
*just really outdated, it exists lol

**Comment by DeathlyPlays** [comment]
ESSB command works, but it's outdated.

**Comment by Stellation** [comment]
*awkward silence*

**Comment by Stellation** [comment]
So merge or nah

**Comment by Stellation** [comment]
Actually, ill remove the comment. But keep the quotes

**Comment by DeathlyPlays** [comment]
Alright

**Pull request merged**
